### PR TITLE
s/_RESUME_INCOMPLETE/_PERMANENT_REDIRECT/

### LINKED ISSUE #11: STATUS_RESUME_INCOMPLETE has a wrong message
In `Hoa\Http\Response\Response`.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #11.

Asking a review from @hoaproject/hoackers.

### CODE REVIEW

**Comment by osaris** [comment]
Permanent direct (308) is specified in RFC 7238 not 7237 ? And it's experimental ...

**Comment by Hywan** [comment]
@osaris Updated. Yes, it's experimental but the previous statutes does not exist so… :-p. Would you prefer to avoid experimental statutes? I guess yes but other libraries implement it :-/.

**Comment by osaris** [comment]
Ok, imo it should not be included as it's experimental but if other are implementing it...

**Comment by Hywan** [comment]
New snapshot.

**Comment by Hywan** [comment]
Thanks @osaris :-).

**Pull request merged**
